parser: babel-eslint

extends:
  - 'airbnb-base'
  - 'plugin:react/recommended'

settings:
  react:
    version: 16.8.4

env:
  node: true
  browser: true
  jest: true

plugins:
  - 'react'

rules:
  import/no-unresolved: 0
  import/extensions: 0
  react/prop-types: 0
  no-console: 0
